server:
  port: 8080
spring:
  application:
    name: concurrency
  cloud:
    nacos:
      discovery:
        server-addr: 114.115.239.109:8847
        username: nacos
        password: Aa123456@
      config:
        server-addr: 114.115.239.109:8847
        username: nacos
        password: Aa123456@
        import-check:
          enabled: false